//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCommon
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int GamesCount { get; set; }
        public int WonsGames { get; set; }
        public int LostGames { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
