//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int Id { get; set; }
        public int RoundId { get; set; }
        public int FirstDice { get; set; }
        public int SecondDice { get; set; }
    
        public virtual Dice Dice { get; set; }
        public virtual Dice Dice1 { get; set; }
        public virtual Round Round { get; set; }
    }
}
